apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: base-node-app
        image: ghcr.io/assafsauer/nodejs-stack:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CONFIG_LOCATION
            value: /config/local.properties
        volumeMounts:
          - mountPath: /config
            name: config
        startupProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          failureThreshold: 15
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          failureThreshold: 15
          initialDelaySeconds: 10
        ports:
          - containerPort: 8080
            protocol: TCP
            name: node-app
      volumes:
        - configMap:
            name: config
          name: config