apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service.fullname" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: {{ .Values.service.ports.protocol }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "k8s-service.selectorLabels" . | nindent 4 }}